### ISSUE TITLE
glowing player.

### ISSUE THREAD

**Issue by DasIstVoltone** [jabelar/MovingLightSource-1.12#7]
The player glows even when the inventory is empty.
![2018-10-18_09 04 50](https://user-images.githubusercontent.com/13628862/47123477-4d720900-d2b6-11e8-8b7c-46565adc3532.png)
Note: used mod "Hardcore Darkness".

**Comment by jabelar** [comment]
Thanks for the report. Did the character hold a lighted item at some point before that? Or did another player with a lighted item pass over this one? Also, did it stop glowing if he moved away?

The way my mod works it places invisible light sources that remember what entity caused them to be placed. It is possible I suppose that a character who held a light and put it away might get out of sync, but all the lights should go away once the character moves more than 2 blocks away from the original location.

But it is also interesting that this mod is called hardcore darkness since that implies it does something with the light -- I'll have to look at how it works, but I guess it could be mucking with the way I create light sources.

**Comment by DasIstVoltone** [comment]
I noticed this when there were not even light sources.

**Comment by jabelar** [comment]
I think I reproduced something similar. There can be a lingering light if an entity is burning and then stops burning. It should go away if the entity moves away though.

By the way, using this mod with Hardcore Darkness is really cool. Definitely a fun mod to use torches in.

Anyway, I know how to fix the issue I found above. I'll fix it and you can see if you still see problems. Hopefully will post a fix by tomorrow.

**Comment by jabelar** [comment]
Okay, I think I fixed it. Version 1.0.7 is now on CurseForge. Let me know if you still see a problem.

Also, I've added flaming arrows -- really fun to use along with the Hardcore Darkness.

**Comment by DasIstVoltone** [comment]
Checked with a light detector from the Project Red mod. The room was insulated with dark glass from the Ender IO mod. Result: the detector saw the player glow giving a signal on the Redstone.
![2018-10-19_08 25 50](https://user-images.githubusercontent.com/13628862/47189975-23821a80-d37a-11e8-818a-ca06cb5827e7.png)
![2018-10-19_08 25 58](https://user-images.githubusercontent.com/13628862/47189976-241ab100-d37a-11e8-8321-c769ffa1063c.png)
![2018-10-19_08 26 02](https://user-images.githubusercontent.com/13628862/47189978-241ab100-d37a-11e8-8ee0-879af43be778.png)
![2018-10-19_08 26 08](https://user-images.githubusercontent.com/13628862/47189979-241ab100-d37a-11e8-94cd-4a5a8d6277c4.png)
![2018-10-19_08 26 13](https://user-images.githubusercontent.com/13628862/47189981-24b34780-d37a-11e8-859e-bd12e42c1b32.png)
![2018-10-19_08 26 14](https://user-images.githubusercontent.com/13628862/47189982-24b34780-d37a-11e8-9d3c-d7bbdd500115.png)

**Comment by jabelar** [comment]
I'm not really familiar with that mod. I can see that your pictures show the blocks activating as you get closer. 

However, is that just your arm in the picture or is that some sort of item being held? Since I don't see anything in your hotbar I'm guessing that is just your arm. 

Basically my mod is really simple -- it will only create light if the item returns a non-zero light value, or else if the entity isBurning() is true. 

I've been testing a lot with the Hardcore Darkness mod (it's a fun mod to combine with mine), and I've never seen the player emit light. In fact most of the time it is so dark that even flipping between items can be "scary".

Are you seeing this like all the time, or just when holding something, or any other clue?

I'll record a video with Hardcore Darkness on to show you that my player isn't seeing any light at all...

**Comment by jabelar** [comment]
Here is video showing gameplay in HardCore Darkness mod. You can see all the light seems to behave properly, and the player is fully dark unless holding the torch. https://youtu.be/5Bnz3LwiyVE

**Comment by DasIstVoltone** [comment]
I could not watch the video. I started the modpack only with Hardcore Darkness and Moving light source. Everything is as it should be. Apparently there is a conflict with some other mod. At the moment I am looking for a conflicting mod.

**Comment by DasIstVoltone** [comment]
Found potentially conflicting mods: Tinkers Construct and Mantle. I'm not sure that this may be the cause of incompatibility, but when these mods are installed in modpack, then my player itself was glowing.

**Comment by jabelar** [comment]
Okay, that is helpful. I'll see if I can reproduce by using those additional mods. I'm really curious though cause I only trigger making light by holding something that emits light or by a burning entity. I can't imagine what those mods are doing, but will see.

**Comment by jabelar** [comment]
Okay, I figured it out. It is interesting but some mods have light-emitting blocks which don't have an associated registered ItemBlock. This caused trouble because then I would consider an AIR block as being the associated item, and of course when a player had nothing in hand it would be "AIR" and so was triggering the light for that mod block.

Will be posted in version 1.0.8 shortly, but I noticed another bug I want to fix before I post the update. Stay tuned.

**Comment by DasIstVoltone** [comment]
Now it works as it should. Thank.
![2018-10-22_22 34 02](https://user-images.githubusercontent.com/13628862/47295748-63cbec00-d64b-11e8-9418-0c5eccda6d8b.png)
![2018-10-22_22 33 47](https://user-images.githubusercontent.com/13628862/47295750-63cbec00-d64b-11e8-8611-c64b10dd56e0.png)
